version: '3'

services:
  deliveries-api:
    image: dr.felicien-fouillet.fr/deliveries-api:latest
    container_name: deliveries-api
    privileged: true
    restart: unless-stopped
    networks:
      - deliveries-api
    ports:
      - 3030:3030

networks:
  deliveries-api:
    external:
      name: docker_default
