version: '3'

services:
  products-api:
    image: dr.felicien-fouillet.fr/products-api:latest
    container_name: products-api
    privileged: true
    restart: unless-stopped
    networks:
      - products-api
    ports:
      - 3030:3030

networks:
  products-api:
    external:
      name: docker_default
