version: '3'

services:
  users-api:
    image: dr.felicien-fouillet.fr/users-api:latest
    container_name: users-api
    privileged: true
    restart: unless-stopped
    networks:
      - users-api
    ports:
      - 3030:3030

networks:
  users-api:
    external:
      name: docker_default
