const doc = {
    info: {
        version: "1.0.0",
        title: "Authentication API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: 'localhost:4000',
    schemes: ['http', 'https'],
}

const swaggerAutogen = require("swagger-autogen")({
    // openapi: '3.0.0',
    swagger: "2.0.0"
});
// 

const outputFile = 'swagger-output.json'
const endpointsFiles = ['./src/controllers/auth.controller.ts']

swaggerAutogen(outputFile, endpointsFiles, doc)